- .vscode/settings.json
- Cargo.toml
- Justfile
- benches/simple.rs
- src/bufpool.rs
- src/lib.rs
This adds a naive (but fast) buffer pool.
It's all hardcoded at 4096 x 4KiB buffers (16MiB total), and leaks memory on thread exit. It doesn't allow refcounting slices (like https://lib.rs/crates/bytes does) yet, and there can never be more than 65536 buffers because the index used is a `u16`.
Everything about it may change, but it's a good enough starting point that I'm going to merge this.
I don't know how to benchmark this properly, these probably don't mean anything.
For one alloc:
For multiple allocs (16 to 4096 buffers), pool vs just `Vec::new`
Details for vec:
Details for pool:
> Add naive buffer pool

- benches/simple.rs
- src/bufpool.rs
Use a `thread_local!` to run thread destructors, because `#[thread_local]` is fast, but doesn't support them. This is only initialized once per thread, so it's still just as cheap.
> Free allocated memory at thread exit

- Cargo.toml
- Justfile
- src/lib.rs
- tests/helpers/fixed_driver.rs
- tests/helpers/mod.rs
- tests/helpers/sample_hyper_server.rs
- tests/helpers/tracing_common.rs
- tests/integration_test.rs
There should be coverage for various buffering shenanigans, invalid HTTP, etc.
> Refactor tests a little, return 431 for headers too large

- Cargo.toml
- Justfile
- src/bufpool.rs
- src/lib.rs
- src/parse/aggregate.rs
- src/parse/http11.rs
- src/parse/mod.rs
- tests/helpers/sample_hyper_server.rs
- tests/integration_test.rs
This introduces `AggregateBuf` which uses several `BufMut` for storage. Its API is supposed to be suitable for reading with io_uring from a socket, and parsing the result with nom.
> Introduce AggregateBuf

- .github/workflows/test.yml
- Justfile
This measures code coverage with `cargo-llvm-cov` and uploads it to codecov.
> Send code coverage info to codecov, closes #10

- src/parse/h1.rs
- src/proto/errors.rs
- src/proto/h1.rs
- src/proto/util.rs
- tests/helpers/sample_hyper_server.rs
- tests/integration_test.rs
This needs a million tests still, and I'm not convinced we need to preserve the chunk size - even if we do, we probably don't need to buffer as much as we currently do.
> Supported chunked transfer-encoding

- src/bufpool/agg.rs
- src/proto/h1.rs
- tests/helpers/mod.rs
Passing an initial buffer is good not specifically for re-use, but for using streams from ktls, where rustls might've decoded some data already.
> Allow passing initial buffer, better errors, add missing grow_if_needed

- rust-toolchain.toml
- src/bufpool/agg.rs
- src/bufpool/mod.rs
- src/io.rs
- src/lib.rs
- src/proto/h1.rs
- src/proto/util.rs
An OwnedRead/OwnedWrite trait would make it much easier to test the HTTP code.
> Mess around with async_fn_in_trait

- rust-toolchain.toml
- src/io.rs
- tests/helpers/mod.rs
We don't necessarily want to establish TCP connections for every single protocol test.
Also we want to be able to trivially test that parses don't blow up when you feed them 1 byte at a time, that sort of thing.
> Introduce some test I/O types

- src/bufpool/agg.rs
- src/bufpool/io_chunk.rs
- src/h1/body.rs
- src/h1/client.rs
- src/h1/parse.rs
- src/h1/server.rs
- src/types/mod.rs
- src/util.rs
- tests/integration_test.rs
- tests/proxy.rs
- tests/testbed.rs
Before this PR, when doing `transfer-encoding: chunked`, chunks were read _entirely_. This could block needlessly.
Now, there's a state machine. Also, the `BodyChunk` enum has been simplified, there's better error handling, `IoChunk` is used instead of having to deal with `AggSlice` separately, there's more utility methods on `AggBuf`, etc.
> Improve streamingness of body reading

- src/bufpool/agg.rs
- src/h1/body.rs
- src/util.rs
- tests/helpers/tracing_common.rs
- tests/integration_test.rs
This tests the `/echo-body` endpoint, with both content-length and chunked transfer encoding bodies.
> Add more tests: echo body (content-len)

- Cargo.toml
- src/buffet/piece.rs
- src/h1/encode.rs
- src/h1/parse.rs
- src/h1/server.rs
- src/types/headers.rs
- src/types/mod.rs
- tests/integration_test.rs
- tests/proxy.rs
This pulls in the `http` crate, which is larged than I'd like, but it gives us solid types for `StatusCode` and `Version`, which I don't care to duplicate right now.
> Keep making API more ergonomic

- src/h2/encode.rs
- src/h2/server.rs
This at least generates a 500 instead of leaving h2 events hanging
> Do minimal error handling when driver returns an error on h2

- .github/workflows/report.yml
- Justfile
- src/h2/server.rs
- src/util.rs
Closes #50, and also, allows reading frames > 4K via `read_and_parse`. Unsure whether that's wise for `Data` frames, we might need special handling there.
> Don't read payload if empty, grow buffer as needed

- .github/workflows/report.yml
- src/buffet/roll.rs
- src/h2/encode.rs
- src/h2/server.rs
There was a TODO and it makes sense to do it that way. `h2_write_loop` is only there so we send messages in-order.
This also sneaks in support for padded header frames, so more h2 tests are actually passing.
> h2: Move parsing logic from write loop to read loop

- src/h2/encode.rs
- src/h2/server.rs
This also gets rid of the `ClientFrame` message.
> h2: Support padded data frames (h2spec generic/3.1)

- src/h2/parse.rs
- src/h2/server.rs
Not working yet, apparently the multiple frames cannot be decoded separately:
```
connection error: 
0: hpack error: StringDecodingError(NotEnoughOctets)
Location:
/home/amos/bearcove/hring/src/h2/server.rs:519
```
This is annoying since the `hpack` crate requires a single contiguous byte slice, but we can do a bit of copying for what should be an edge case (large headers + small frame size).
> h2: Support CONTINUATION frames (wip)

- crates/hring-hpack/README.md
- crates/hring-hpack/src/lib.rs
While looking at the upstream hpack repo, saw a PR,
https://github.com/mlalic/hpack-rs/pull/7
that seems correct to me.
I think the PR would have been merged but the repo seems to no longer be supported.
Quoting from xpepermint:
I found a serious bug in the static table - an invalid entry.
Ref: https://tools.ietf.org/html/rfc7541#appendix-A
While at it, might as well pull in the only other PR at this time from the upstream hpack repo.
https://github.com/mlalic/hpack-rs/pull/4
It doesn't affect the build as it is just a change to the README.md but some people found and filed the issue, and one went so far as to propose this fix. (I haven't tried the fix.)
> fix hpack static entries and the README

- crates/hring/src/h2/server.rs
Should fix four failing test cases from h2spec
8.1.2.3. Request Pseudo-Header Fields
❌ Sends a HEADERS frame with empty ":path" pseudo-header field
GOAWAY Frame (Error Code: PROTOCOL_ERROR)
✅ Sends a HEADERS frame that omits ":method" pseudo-header field
✅ Sends a HEADERS frame that omits ":scheme" pseudo-header field
✅ Sends a HEADERS frame that omits ":path" pseudo-header field
❌ Sends a HEADERS frame with duplicated ":method" pseudo-header field
GOAWAY Frame (Error Code: PROTOCOL_ERROR)
❌ Sends a HEADERS frame with duplicated ":scheme" pseudo-header field
GOAWAY Frame (Error Code: PROTOCOL_ERROR)
❌ Sends a HEADERS frame with duplicated ":path" pseudo-header field
GOAWAY Frame (Error Code: PROTOCOL_ERROR)
Also rejects when duplicate `authority` pseudo-headers are encountered although …
> Fix h2spec Request Pseudo-Hader Fields

- crates/hring-buffet/src/io.rs
- rust-toolchain.toml
No need to go through a freestanding `writev_all` function anymore!
> Revert workaround for default async methods, closes #85

- crates/hring-bingo-ktls/src/main.rs
- crates/hring-buffet/src/io.rs
- crates/hring-buffet/src/io/buf_or_slice.rs
- crates/hring-buffet/src/io/chan.rs
- crates/hring-buffet/src/io/non_uring.rs
- crates/hring-buffet/src/io/uring_tcp.rs
- crates/hring-buffet/src/roll.rs
- crates/hring/src/h1/body.rs
- crates/hring/src/h1/client.rs
- crates/hring/src/h1/encode.rs
- crates/hring/src/h1/server.rs
- crates/hring/src/h2/server.rs
- crates/hring/src/util.rs
- crates/hring/tests/integration_test.rs
- crates/hring/tests/proxy.rs
- test-crates/hring-h2spec/src/non_uring.rs
- test-crates/hring-h2spec/src/uring.rs
Still prep work for #93 - this allows eschewing `RefCell` for the non-uring codepaths.
> Take `&mut self` for ReadOwned and WriteOwned

- crates/hring-buffet/Cargo.toml
- crates/hring/Cargo.toml
- crates/hring/src/h2/encode.rs
- crates/hring/src/h2/server.rs
- crates/hring/src/lib.rs
- test-crates/hring-h2spec/Cargo.toml
- test-crates/hring-h2spec/src/main.rs
- test-crates/hring-h2spec/src/non_uring.rs
"cargo run --no-default-features" now works. We can't yet pull tokio-uring only on non-Linux platforms but... we'll get there at some point?
Closes #93
> Allow running h2spec without io-uring

- rust-toolchain.toml
Among other things, "sparse" is the default as of 5 days ago, which might help in CI: https://github.com/rust-lang/cargo/pull/11791
> bump to nightly-2023-03-07

- .github/workflows/test.yml
- crates/hring-bingo-ktls/Cargo.toml
- crates/hring-h2spec/src/main.rs
- crates/hring-hpack/src/huffman.rs
- rust-toolchain.toml
This is currently blocked on https://github.com/rust-lang/rust/issues/114858
Which is apparently solved by https://github.com/rust-lang/rust/pull/115215
But maybe not completely? https://github.com/rust-lang/rust/pull/115215#issuecomment-1710401747
> Upgrade to 2023-09-13

- crates/fluke-tls-sample/Cargo.toml
Notably, this bumps rustls and tokio-rustls. 3.0.0 was yanked for a while, and now 3.0.2 is a version we can depend on.
See https://github.com/hapsoc/ktls/blob/main/CHANGELOG.md#300-2023-06-14-yanked
> chore: Upgrade to ktls v3

- crates/fluke-hpack/src/decoder.rs
- crates/fluke-hpack/src/encoder.rs
- crates/fluke-hpack/src/huffman.rs
- crates/fluke/src/h2/encode.rs
- crates/fluke/src/h2/server.rs
Aiming to fix `http2/5.1/3` (receiving WINDOW_UPDATE on an idle stream is a connection error) but just reducing indentation for now
> fix: Treat WINDOW_UPDATE on idle stream as a protocol error

- crates/fluke/src/h2/read.rs
- crates/fluke/src/h2/server.rs
- crates/fluke/src/h2/types.rs
- test-crates/fluke-h2spec/src/main.rs
> Graceful GOAWAY handling

- Cargo.lock
- Cargo.toml
- Justfile
- crates/fluke-buffet/Cargo.toml
- crates/fluke-buffet/src/lib.rs
- crates/fluke-buffet/src/net/net_uring.rs
- crates/fluke-curl-tests/Cargo.toml
- crates/fluke-h2-parse/Cargo.toml
- crates/fluke-h2-parse/src/lib.rs
- crates/fluke-hpack/Cargo.toml
- crates/fluke-httpwg-server/src/main.rs
- crates/fluke-hyper-testbed/Cargo.toml
- crates/fluke-io-uring-async/Cargo.toml
- crates/fluke-io-uring-async/src/linux.rs
- crates/fluke-tls-sample/Cargo.toml
- crates/fluke/Cargo.toml
- crates/fluke/tests/httpwg2.rs
- crates/httpwg-cli/Cargo.toml
- crates/httpwg-cli/src/main.rs
- crates/httpwg-gen/Cargo.toml
- crates/httpwg-gen/src/ast.rs
- crates/httpwg/Cargo.toml
- crates/httpwg/src/lib.rs
- crates/httpwg/src/rfc9113/_8_expressing_http_semantics_in_http2.rs
- rust-toolchain.toml
The main problem of running those is cleanup of async ops: there's a "read HTTP/2 frames" loop in httpwg, and that entire task gets dropped after the test is finished (when shutting down the runtime), which results in `Op drop occured before completion (index 0)` messages):
```shell
amos in 🌐 brat in fluke on  httpwg-cli-p2 [!] via 🦀 v1.80.1 took 4s
❯ RUST_LOG=debug RUST_BACKTRACE=0 just httpwg-over-tcp -t 3000 -f 'path'
cargo build --release --package fluke-httpwg-server --package httpwg-cli
Blocking waiting for file lock on package cache
Compiling httpwg v0.1.1 (/home/amos/bearcove/fluke/crates/httpwg)
Compiling httpwg-cli v0.1.0 (/home/amos/bearcove/fluke/crates/httpwg-cli)
Finished `release` profile [optimized + debuginfo] target(s) in 1.44s
./target/release/httpwg --address …
```
> chore: Upgrade dependencies + investigate async cancellation issues

- crates/fluke-buffet/src/lib.rs
- crates/httpwg-cli/src/main.rs
This cancels the `IoUringAsync::listen` task in fluke-buffet before waiting for the LocalSet to finish.
That's a clean-up follow-up to #198
> chore: More async cancellation cleanups

- README.md
Just a small correction of the README to point to luring instead of the delicious buffet.
> docs: Luring link corrected
