bearcove/loona

.github/workflows/test.yml
src/bufpool.rs
tests/integration_test.rs

Still using persistent runners, using local sccache storage, better than nothing 🤷

Use sccache in CI

---

src/bufpool.rs
src/lib.rs

This uses the new buffer pool in the h1 proxy code.
`Vec`s are still used to accumulate headers, which isn't great, I do want to get rid of that at some point - that's copying that doesn't really need to happen.

Use buffer pool in serve_h1

---

benches/simple.rs
src/bufpool.rs
src/lib.rs

This tackles ref counting of mutable/immutable buffers.

Introduce BufMut / Buf split

---

src/parse/h1.rs

There was some dead code in there, and some parsers were less useful than they should've been.

Clean up parsers a little bit

---

.github/workflows/test.yml
Cargo.toml
hyper-testbed/Cargo.toml
hyper-testbed/src/main.rs
src/h1/body.rs
src/h1/client.rs
src/h1/server.rs
src/types/headers.rs
src/types/mod.rs
tests/integration_test.rs
tests/proxy.rs

..which reveal that we should support 100-continue

Add some curl tests

---

src/h2/server.rs
src/h2/server/parse.rs

```shell
h2spec -p 8888 http2/4.1/1
Hypertext Transfer Protocol Version 2 (HTTP/2)
4. HTTP Frames
4.1. Frame Format
✔ 1: Sends a frame with unknown type
Finished in 0.0043 seconds
1 tests, 1 passed, 0 skipped, 0 failed
```

h2: Ignore unknown frames (http2/4.1/1), closes #46

---

.github/workflows/report.yml
.github/workflows/test.yml
.gitignore
Justfile
h2spec-server/Cargo.toml
h2spec-server/src/main.rs
rust-toolchain.toml

Better h2spec tracking

---

Justfile

hpack: Run interop tests

---

crates/hring-buffet/src/io.rs
crates/hring/src/h1/body.rs
crates/hring/src/h1/client.rs
crates/hring/src/h1/encode.rs
crates/hring/src/h1/server.rs
crates/hring/src/h2/parse.rs
crates/hring/src/h2/server.rs
crates/hring/src/util.rs

WriteOwned::writev: Return early in case of partial writes

---

crates/hring/src/h2/server.rs

Reject priority specs that depend on themselves

---

crates/hring/src/h2/parse.rs
crates/hring/src/h2/server.rs

http2: Check stream ids

---

crates/hring-bingo-ktls/src/main.rs
crates/hring-buffet/Cargo.toml
crates/hring-buffet/src/io.rs
crates/hring-buffet/src/roll.rs
crates/hring/Cargo.toml
crates/hring/src/h1/body.rs
crates/hring/src/h1/client.rs
crates/hring/src/h1/encode.rs
crates/hring/src/h1/server.rs
crates/hring/src/h2/parse.rs
crates/hring/src/h2/server.rs
crates/hring/src/responder.rs
crates/hring/tests/integration_test.rs
crates/hring/tests/proxy.rs
test-crates/hring-h2spec/Cargo.toml
test-crates/hring-h2spec/src/main.rs
test-crates/hring-h2spec/src/non_uring.rs
test-crates/hring-h2spec/src/uring.rs

Introduce SplitOwned, have h2 use separate parts

---

.github/workflows/test.yml
crates/hring-h2spec/Cargo.toml

Thanks to rain for mentioning this!

Use an action to install nextest, force color

---

crates/hring/src/h2/end_headers.rs
crates/hring/src/h2/mod.rs
crates/hring/src/h2/server.rs

Still really messy, the h2 internals will take a while to figure out a natural structure for.

Clean up header/trailer handling, closes #84

---

.github/workflows/test.yml

cf. https://github.com/hapsoc/fluke/issues/118

Try out sccache action for macos & win flows

---

.github/workflows/test.yml
crates/fluke/src/h2/read.rs
crates/fluke/src/h2/types.rs

Have a few methods return H2Result, which clarifies the control flow

---

crates/fluke-buffet/src/lib.rs
crates/fluke-maybe-uring/src/io.rs
crates/fluke-maybe-uring/src/lib.rs
crates/fluke/src/h1/client.rs
crates/fluke/src/lib.rs
crates/fluke/src/responder.rs
crates/fluke/src/types/mod.rs
rust-toolchain.toml
test-crates/fluke-curl-tests/tests/integration_test.rs
test-crates/fluke-curl-tests/tests/proxy.rs
test-crates/fluke-h2spec/src/main.rs
test-crates/fluke-tls-sample/src/main.rs
test-crates/hyper-testbed/src/main.rs

- Upgrade to 2023-10-18, closes #117
- Opt out of async_fn_in_trait warnings

Upgrade to 2023-10-18, closes #117

---

.github/workflows/test.yml
Justfile
crates/fluke-buffet/src/piece.rs
crates/fluke/src/h2/body.rs
crates/fluke/src/h2/parse.rs
crates/fluke/src/h2/read.rs
crates/fluke/src/h2/server.rs
crates/fluke/src/h2/types.rs
crates/fluke/src/h2/write.rs
crates/fluke/src/util.rs
test-crates/fluke-h2spec/src/main.rs

feat: Remove continuation state, simplifies code greatly

---

Cargo.lock
crates/fluke-maybe-uring/Cargo.toml
crates/fluke-maybe-uring/src/io.rs
crates/fluke-maybe-uring/src/io/chan.rs
crates/fluke-maybe-uring/src/io/non_uring.rs
crates/fluke-maybe-uring/src/lib.rs
crates/fluke-maybe-uring/src/net/net_noring.rs
crates/fluke-maybe-uring/src/net/net_uring.rs
crates/fluke/src/h1/mod.rs
crates/fluke/src/h1/parse.rs
crates/fluke/src/h2/encode.rs
crates/fluke/src/h2/mod.rs
crates/fluke/src/h2/parse.rs
crates/fluke/src/h2/server.rs
crates/fluke/src/h2/types.rs
crates/fluke/src/responder.rs
crates/fluke/src/types/method.rs
test-crates/fluke-curl-tests/Cargo.lock
test-crates/fluke-h2spec/Cargo.lock
test-crates/fluke-h2spec/src/main.rs
test-crates/fluke-tls-sample/Cargo.lock

Now to 70 passing tests, which is one better than before The Great Refactor :)

feat: Disable nagle for testing, simulate delay, fix more h2spec cases

---

.github/workflows/test.yml
crates/httpwg-gen/src/ast.rs
crates/httpwg/src/rfc9113/_4_2_frame_size.rs

Run httpwg-gen in CI, assert there's no changes

---

.cargo-husky/hooks/pre-commit
Cargo.lock
crates/fluke/Cargo.toml

Runs `httpwg-gen` before committing. Closes #178

Try out pre-commit hook

---

.cargo/config.toml
crates/fluke-buffet/src/bufpool.rs
crates/fluke-buffet/src/bufpool/privatepool.rs
crates/fluke-buffet/src/lib.rs
crates/fluke-buffet/src/roll.rs
crates/fluke/Cargo.toml
crates/fluke/benches/encoding.rs
rust-toolchain.toml

It would be nice to be on stable. We'll see if the perf is acceptable.

feat: Try going back to stable with LocalKey and no nightly features

---

Cargo.lock
crates/fluke-httpwg-server/src/main.rs
crates/fluke-hyper-testbed/Cargo.toml
crates/fluke-hyper-testbed/src/main.rs

fix: Set TCP_NODELAY on io_uring path

---

.github/workflows/test.yml
Cargo.lock
crates/loona/Cargo.toml

feat!: Upgrade to ktls@6.0.0

---

.github/workflows/test.yml
Justfile
crates/buffet/src/io.rs
crates/httpwg-macros/src/lib.rs
crates/httpwg/src/rfc9113/_8_expressing_http_semantics_in_http2.rs
crates/loona-h2/src/lib.rs
crates/loona-hpack/src/lib.rs
crates/loona/src/h1/parse.rs
crates/loona/src/h2/server.rs

Build docs in CI, deny warnings

---

Cargo.lock
Justfile
crates/httpwg-cli/Cargo.toml
crates/httpwg-cli/src/main.rs
crates/httpwg-gen/src/main.rs
crates/httpwg-loona/Cargo.toml
crates/httpwg-loona/src/main.rs
crates/httpwg-macros/src/lib.rs
crates/httpwg/src/lib.rs
crates/loona/src/h2/server.rs

..and use it in httpwg-cli to run _all_ tests over TCP.
Closes #199

feat: Generate catalog in httpwg-macros

---

.github/workflows/test.yml
Justfile
crates/buffet/src/bufpool.rs
crates/buffet/src/net/net_uring.rs

feat: Run miri in CI
